---
- name: Retrieve user home directory for current logged user
  ansible.builtin.set_fact:
    user_home_dir: "{{ ansible_env.HOME }}"
    user: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  when: aws_workspace_tweaks_user | length == 0

- name: Retrieve user home directory for {{ aws_workspace_tweaks_user }}
  ansible.builtin.user:
    name: "{{ aws_workspace_tweaks_user }}"
    state: present
  register: certificate_user_register
  when: aws_workspace_tweaks_user | length > 0

- name: Set facts user home directory for {{ aws_workspace_tweaks_user }}
  ansible.builtin.set_fact:
    user_home_dir: "{{ certificate_user_register.home }}"
    user: "{{ aws_workspace_tweaks_user }}"
    group: "{{ aws_workspace_tweaks_user }}"
  when: aws_workspace_tweaks_user | length > 0

- name: "Firefox: check if profile exists" 
  ansible.builtin.stat:
    path: "{{ user_home_dir }}/.mozilla"
  register: firefox_profile

- name: "Chrome: check if certificates db exists" 
  ansible.builtin.stat:
    path: "{{ user_home_dir }}/.pki/nssdb"
  register: chrome_certificate_db

- name: Copy CommisSign root certificate on the target.
  ansible.builtin.copy:
    src: RootCA.crt
    dest: /tmp
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  register: root_certificate

- name: "Firefox: import CommisSign root certificate."
  ansible.builtin.command: |
    bash -c "
    for certDB in $(find \"{{ user_home_dir }}/.mozilla\" -iname \"cert9.db\"); do 
      certDir=$(dirname ${certDB});
      certutil -A -d sql:${certDir} -n \"CommisSign-2 Root CA\" -t C,C,C -i {{ root_certificate.dest }}
    done"
  changed_when: false
  become: true
  become_user: "{{ user }}"
  when: firefox_profile.stat.exists

- name: "Chrome: import CommisSign root certificate."
  ansible.builtin.command: "certutil -A -d sql:{{ user_home_dir }}/.pki/nssdb -n \"CommisSign-2 Root CA\" -t C,C,C -i {{ root_certificate.dest }}"
  changed_when: false
  become: true
  become_user: "{{ user }}"
  when: chrome_certificate_db.stat.exists
