---
- name: Include ssm agent tasks.
  ansible.builtin.include_tasks: ssm-agent.yml

- name: Include tasks to apply security updates.
  ansible.builtin.include_tasks: security-updates.yml

- name: Include tasks to import CommisSign root certificate.
  ansible.builtin.include_tasks: commissign-certificate.yml
