---
- name: Apply security updates
  become: true
  ansible.builtin.yum:
    name: '*'
    state: latest
    bugfix: false
    security: true
    update_only: true
  when:
    - aws_workspace_tweaks_apply_security_updates|bool
