---
- name: Converge
  hosts: all
  vars:
    aws_workspace_tweaks_user: ansible
  tasks:
    - name: Include aws_workspace_tweaks
      ansible.builtin.include_role:
        name: "aws_workspace_tweaks"
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
