---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Include tasks to verify SSM agent.
      ansible.builtin.include_tasks: verify-ssm-agent.yml
    - name: Include tasks to verify CommisSign root certificate.
      ansible.builtin.include_tasks: verify-commissign-certificate.yml
      vars:
        aws_workspace_tweaks_user: ansible
